// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ns
Rcpp::List ns(const arma::mat& x, const arma::vec& y, const arma::vec& k, const arma::vec& h, const unsigned max_ns_iter, const unsigned max_gd_iter, const double eps);
RcppExport SEXP _robustsubsets_ns(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP hSEXP, SEXP max_ns_iterSEXP, SEXP max_gd_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h(hSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type max_ns_iter(max_ns_iterSEXP);
    Rcpp::traits::input_parameter< const unsigned >::type max_gd_iter(max_gd_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(ns(x, y, k, h, max_ns_iter, max_gd_iter, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robustsubsets_ns", (DL_FUNC) &_robustsubsets_ns, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_robustsubsets(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
