# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ns <- function(x, y, k, h, max_ns_iter, max_gd_iter, eps) {
    .Call(`_robustsubsets_ns`, x, y, k, h, max_ns_iter, max_gd_iter, eps)
}

