# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gd <- function(X, y, beta, eta, k, h, step, max_iter, tol) {
    .Call(`_robustsubsets_gd`, X, y, beta, eta, k, h, step, max_iter, tol)
}

